
CREATE DATABASE DATABASE_EXAMEN_U2
GO
USE DATABASE_EXAMEN_U2
GO
--CREACIÓN DE TABLAS
--TABLA ARTICULOS
CREATE TABLE ARTICULOS(
ARTID INT NOT NULL,
ARTNOMBRE NVARCHAR(30) NOT NULL,
ARTMDESCIPCION NVARCHAR(100) NOT NULL,
ARTPRECIO NUMERIC(10, 2) NOT NULL,
ARTPAQUETE INT)
GO
--TABLA ENVIOS
CREATE TABLE ENVIOS(
BODID INT NOT NULL,
FOLIO INT NOT NULL,
FECHA DATETIME NOT NULL,
ARTID INT NOT NULL,
CANTIDAD NUMERIC(10, 2) NOT NULL,
PRECIO NUMERIC(10, 2) NOT NULL)
GO
--TABLA BODEGAS
CREATE TABLE BODEGAS(
BODID INT NOT NULL,
BODNOMBRE NVARCHAR(30) NOT NULL,
BODDOMICILIO NVARCHAR(50) NOT NULL,
TIPOID INT NOT NULL)
GO
--TABLA TIPOS
CREATE TABLE TIPOS(
TIPOID INT NOT NULL,
TIPONOMBRE NVARCHAR(30) NOT NULL
)
GO
--LLAVES PRIMARIAS
--PK ARTICULOS
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ART PRIMARY KEY(ARTID)
GO
--PK ENVIOS
ALTER TABLE ENVIOS ADD CONSTRAINT PK_ENV PRIMARY KEY(FOLIO,BODID)
GO
--PK BODEGAS
ALTER TABLE BODEGAS ADD CONSTRAINT PK_BOD PRIMARY KEY(BODID)
GO
--PK TIPOS
ALTER TABLE TIPOS ADD CONSTRAINT PK_TIP PRIMARY KEY(TIPOID)
GO
--DEFINICIÓN DE LAS LLAVES FORANEAS
--BODEGAS/TIPOS
ALTER TABLE BODEGAS
ADD CONSTRAINT FK_BOD_TIP FOREIGN KEY(TIPOID) REFERENCES TIPOS(TIPOID)
GO
--ENVIOS/BODEGAS
ALTER TABLE ENVIOS
ADD CONSTRAINT FK_ENV_BOD FOREIGN KEY(BODID) REFERENCES BODEGAS(BODID)
GO
--ENVIO/ARTICULOS
ALTER TABLE ENVIOS
ADD CONSTRAINT FK_ENV_ART FOREIGN KEY(ARTID) REFERENCES ARTICULOS(ARTID)
GO
--LLAVES UNICAS
ALTER TABLE BODEGAS ADD
CONSTRAINT UC_BOD_TIP UNIQUE(TIPOID)
GO
--RESTRICCIONES
ALTER TABLE ENVIOS ADD
CONSTRAINT CC_ENV_FECHA CHECK(FECHA >= '1-1-2000'),
CONSTRAINT CC_ENV_PRECIO CHECK(PRECIO> 0)
GO
ALTER TABLE ARTICULOS ADD
CONSTRAINT CC_ART_PRECIO CHECK(ARTPRECIO> 0)
GO
