CREATE DATABASE FERRETERIAS
GO
USE FERRETERIAS
GO
--CREACIÓN DE TABLAS
--TABLA FERRETERIAS
CREATE TABLE FERRETERIAS(
FERRID INT NOT NULL ,
FERRNOMBRE NVARCHAR(50) NOT NULL,
FERRDOMICILIO NVARCHAR(50) NOT NULL,
FERRTELEFONO NCHAR(10) NOT NULL
)
go
--TABLA ZONAS
CREATE TABLE ZONAS(
ZONAID INT NOT NULL ,
ZONANOMBRE NVARCHAR(50) NOT NULL,
)
GO
--TABLA EMPLEADOS
CREATE TABLE EMPLEADOS(
EMPID INT NOT NULL ,
EMPNOMBRE NVARCHAR(50) NOT NULL,
EMPAPEPAT NVARCHAR(50) NOT NULL,
EMPAPEMAT NVARCHAR(50) NOT NULL,
EMPDOMICILIO NVARCHAR(50) NOT NULL,
EMPTELEFONO  NCHAR(10) NOT NULL,
EMPCELULAR  NCHAR(10) NOT NULL,
EMPRFC NCHAR(13) NULL,
EMPCURP  NCHAR(18) NULL,
EMPFECHAINGRESO  DATETIME NOT NULL,
EMPFECHANACIMIENTO DATETIME NOT NULL,
ZONAID INT NOT NULL,
JEFE INT,
)
GO
--TABLA COLONIAS
CREATE TABLE COLONIAS(
COLID INT NOT NULL,
COLNOMBRE NVARCHAR(50) NOT NULL,
COLCP NCHAR(5) NOT NULL,
MUNID INT NOT NULL)
GO
--TABLA MUNICIPIOS
CREATE TABLE MUNICIPIOS(
MUNID INT NOT NULL,
MUNNOMRE NVARCHAR(50) NOT NULL,
)
GO
--TABLA FAMILIAS
CREATE TABLE FAMILIAS(
FAMID INT NOT NULL,
FAMNOMBRE NVARCHAR(50) NOT NULL)
GO
--TABLA CLEINTES
CREATE TABLE CLIENTES(
CTEID INT NOT NULL,
CTENOM NVARCHAR(50) NOT NULL,
CTEAPEPAT NVARCHAR(50) NOT NULL,
CTEAPMAT NVARCHAR(50) NOT NULL,
CTEDOMICILIO NVARCHAR(50) NOT NULL,
CTETELEFONO NCHAR(10) NOT NULL,
CTECELULAR NCHAR(10) NOT NULL,
CTERFC NCHAR(13) NULL,
CTECURP NCHAR(18) NULL,
CTEFECHANACIMIENTO DATETIME NOT NULL,
CTESEX NCHAR(1) NOT NULL,
COLID INT NOT NULL)
GO
--TABLA DETALLE (ARTICULOS X VENTAS)
CREATE TABLE DETALLE(
FOLIO INT NOT NULL,
ARTID INT NOT NULL,
CANTIDAD NUMERIC(10, 2) NOT NULL,
PRECIO NUMERIC(10, 2) NOT NULL)
GO
--TABLA VENTAS
CREATE TABLE VENTAS(
FOLIO INT NOT NULL,
FECHA DATETIME NOT NULL,
FERTID INT NOT NULL,
CTEID INT NOT NULL,
EMPID INT NOT NULL
)
--TABLA ARTICULOS
CREATE TABLE ARTICULOS(
ARTID INT NOT NULL,
ARTNOMBRE NVARCHAR(30) NOT NULL,
ARTMDESCIPCION NVARCHAR(100) NOT NULL,
ARTPRECIO NUMERIC(10, 2) NOT NULL,
FAMID INT NOT NULL)
GO
--LLAVES PRIMARIAS
--PK EMPLEADOS
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMP PRIMARY KEY(EMPID)
GO
--PK FERRETERIAS
ALTER TABLE FERRETERIAS ADD CONSTRAINT PK_FER PRIMARY KEY(FERRID)
GO
--PK ZONAS
ALTER TABLE ZONAS ADD CONSTRAINT PK_ZON PRIMARY KEY(ZONAID)
GO
--PK VENTAS
ALTER TABLE VENTAS ADD CONSTRAINT PK_VEN PRIMARY KEY(FOLIO)
GO
--PK DETALLE (ARTICULOS X VENTAS)
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMP PRIMARY KEY(FOLIO,ARTID)
GO
--PK ARTICULOS
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ART PRIMARY KEY(ARTID)
GO
--PK FAMILIAS
ALTER TABLE FAMILIAS ADD CONSTRAINT PK_FAM PRIMARY KEY(FAMID)
GO
--PK COLONIAS
ALTER TABLE COLONIAS ADD CONSTRAINT PK_COL PRIMARY KEY(COLID)
GO
--PK MUNICIPIOS
ALTER TABLE MUNICIPIOS ADD CONSTRAINT PK_MUN PRIMARY KEY(MUNID)
GO
--PK CLIENTES
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CTE PRIMARY KEY(CTEID)
GO
--DEFINICIÓN DE LAS LLAVES FORANEAS

--COLONIAS/MUNICIPIOS
ALTER TABLE COLONIAS
ADD CONSTRAINT FK_COL_MUN FOREIGN KEY(MUNID) REFERENCES MUNICIPIOS(MUNID)
GO
--CLIENTES/COLONIAS
ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CLE_COL FOREIGN KEY(COLID) REFERENCES COLONIAS(COLID)
GO
--ARTICULOS/FAMILIAS
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_ART_FAM FOREIGN KEY(FAMID) REFERENCES FAMILIAS(FAMID)
GO
--DETALLE/ARTICULOS
ALTER TABLE DETALLE
ADD CONSTRAINT FK_DET_ART FOREIGN KEY(ARTID) REFERENCES ARTICULOS(ARTID)
GO
--DETALLE/VENTAS
ALTER TABLE DETALLE
ADD CONSTRAINT FK_DET_VEN FOREIGN KEY(FOLIO) REFERENCES VENTAS(FOLIO)
GO
--EMPLEADOS/ZONAS
ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_EMP_ZON FOREIGN KEY(ZONAID) REFERENCES ZONAS(ZONAID)
GO
--VENTAS/FERRERIAS
ALTER TABLE VENTAS
ADD CONSTRAINT FK_VEN_FER FOREIGN KEY(FERRID) REFERENCES FERRETERIAS(FERRID)
GO
--VENTAS/CLIENTES
ALTER TABLE VENTAS
ADD CONSTRAINT FK_VEN_CLE FOREIGN KEY(CTEID) REFERENCES CLIENTES(CTEID)
GO
--VENTAS/EMPLEADOS
ALTER TABLE VENTAS
ADD CONSTRAINT FK_VEN_EMP FOREIGN KEY(EMPID) REFERENCES EMPLEADOS(EMPID)
GO
--LLAVES UNICAS
ALTER TABLE CLIENTES ADD
CONSTRAINT UC_CLE_RFC UNIQUE(CTERFC),
CONSTRAINT UC_CLE_CURP UNIQUE(CTECURP)
GO
ALTER TABLE EMPLEADOS ADD
CONSTRAINT UC_EMP_RFC UNIQUE(EMPRFC),
CONSTRAINT UC_EMP_CURP UNIQUE(EMPCURP)
GO
--RESTRICCIONES
--ARTICULOS
ALTER TABLE ARTICULOS ADD
CONSTRAINT CC_ART_COSTO CHECK(ARTPRECIO > 0)
GO
--DETALLE
ALTER TABLE DETALLE ADD
CONSTRAINT CC_DET_PRECIO CHECK(PRECIO> 0)
GO
--VENTAS
ALTER TABLE VENTAS ADD
CONSTRAINT CC_VEN_FECHA CHECK(FECHA >= '1-1-2000')
GO
--EMPLEADOS
ALTER TABLE EMPLEADOS ADD
CONSTRAINT CC_EMP_RFC_CURP CHECK(EMPRFC <> EMPCURP),
CONSTRAINT CC_EMP_SEX CHECK(EMPSEX IN('F', 'M'))
GO
--CLIENTES
ALTER TABLE CLIENTES ADD
CONSTRAINT CC_CLE_RFC_CURP CHECK(CLERFC <> CLECURP),
CONSTRAINT CC_CLE_SEX CHECK(USERSEX IN('F', 'M'))